// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vNAltnk7YuiZwhF5E-kTmwcI1mfkA30',
    appId: '1:877193206753:web:2ddcbdd83a4a53db8010a0',
    messagingSenderId: '877193206753',
    projectId: 'eos-chatting-b90b3',
    authDomain: 'eos-chatting-b90b3.firebaseapp.com',
    storageBucket: 'eos-chatting-b90b3.appspot.com',
    measurementId: 'G-M4B8JR3WZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GCLhImGyV2dpIgvEuzMpcRKbu-2x44Y',
    appId: '1:877193206753:android:2f96f678ceb0fcc58010a0',
    messagingSenderId: '877193206753',
    projectId: 'eos-chatting-b90b3',
    storageBucket: 'eos-chatting-b90b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvxXyfTRIa7zREqjQx6KCBv5ir0nRGKlQ',
    appId: '1:877193206753:ios:444e30bc89b028a98010a0',
    messagingSenderId: '877193206753',
    projectId: 'eos-chatting-b90b3',
    storageBucket: 'eos-chatting-b90b3.appspot.com',
    iosClientId: '877193206753-hjn7vkliivk9cb894qubrf251vnm3odq.apps.googleusercontent.com',
    iosBundleId: 'com.example.week2Assginment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvxXyfTRIa7zREqjQx6KCBv5ir0nRGKlQ',
    appId: '1:877193206753:ios:444e30bc89b028a98010a0',
    messagingSenderId: '877193206753',
    projectId: 'eos-chatting-b90b3',
    storageBucket: 'eos-chatting-b90b3.appspot.com',
    iosClientId: '877193206753-hjn7vkliivk9cb894qubrf251vnm3odq.apps.googleusercontent.com',
    iosBundleId: 'com.example.week2Assginment',
  );
}
